services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: production
      args:
        USER_ID: $PUID
        GROUP_ID: $PGID
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:8080'
      - '${APP_SSL_PORT:-443}:8443'
    environment:
      - SSL_MODE=mixed
      - PHP_POOL_NAME=web_${APP_ENV}
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILE_SIZE=100M
      - AUTORUN_ENABLED=true
    volumes:
      - .:/var/www/html/
    networks:
        - intermediano
    restart: always
  queue:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: production
      args:
        USER_ID: $PUID
        GROUP_ID: $PGID
    command: ["php", "/var/www/html/artisan", "queue:work", "--timeout=600", "--tries=1"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PHP_POOL_NAME=queue_${APP_ENV}
    volumes:
      - .:/var/www/html/
    networks:
      - intermediano
    restart: always
  task:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: production
      args:
        USER_ID: $PUID
        GROUP_ID: $PGID
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PHP_POOL_NAME=task_${APP_ENV}
    volumes:
      - .:/var/www/html/
    networks:
      - intermediano
    restart: always
networks:
    intermediano:
        driver: bridge
